# Generated by Django 6.0.7 on 2026-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_shared_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
