# Generated by Django 6.0.7 on 2026-08-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='palette',
            field=models.CharField(choices=[('violet', 'Фіолет'), ('ocean', 'Океан'), ('forest', 'Ліс'), ('sunset', 'Захід'), ('mono', 'Монохром')], default='violet', max_length=10),
        ),
    ]
